name: PR Checks

on: # Rebuild any PRs and main branch changes
  push:
    branches:
      - main
  pull_request:


jobs:

  install-node-modules:
    name: Install Dependencies - Node ${{ matrix.node }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node: [ 16, 18, 20 ]

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node }}
          cache: yarn
      - name: Validate cache
        run: yarn install --immutable

  test:
    name: Run Jest Tests - Node ${{ matrix.node }}
    runs-on: ubuntu-latest
    needs: install-node-modules
    strategy:
      matrix:
        node: [ 16, 18, 20 ]

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node }}
          cache: yarn
      - name: install
        run: yarn install --immutable
      - name: test
        run: yarn test

  lint:
    name: Run Lints
    runs-on: ubuntu-latest
    needs: install-node-modules

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: yarn
      - name: install
        run: yarn install --immutable
      - name: lint
        run: yarn lint
      - name: markdown lint
        run: yarn lint:md

  prettier:
    name: Check Formatting
    runs-on: ubuntu-latest
    needs: install-node-modules

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: yarn
      - name: install
        run: yarn install --immutable
      - name: format-check
        run: yarn format:check
